import { MD3Typescale } from "react-native-paper/lib/typescript/types";

export const typography: MD3Typescale = {
  default: {
    fontFamily: "System",
    fontWeight: "400",
    letterSpacing: 0,
  },
  displayLarge: {
    fontFamily: "System",
    fontWeight: "700",
    fontSize: 36,
    lineHeight: 44,
    letterSpacing: 0,
  },
  displayMedium: {
    fontFamily: "System",
    fontWeight: "700",
    fontSize: 32,
    lineHeight: 40,
    letterSpacing: 0,
  },
  displaySmall: {
    fontFamily: "System",
    fontWeight: "700",
    fontSize: 28,
    lineHeight: 36,
    letterSpacing: 0,
  },

  headlineLarge: {
    fontFamily: "System",
    fontWeight: "600",
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: 0,
  },
  headlineMedium: {
    fontFamily: "System",
    fontWeight: "600",
    fontSize: 20,
    lineHeight: 28,
    letterSpacing: 0,
  },
  headlineSmall: {
    fontFamily: "System",
    fontWeight: "600",
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0,
  },
  titleLarge: {
    fontFamily: "System",
    fontWeight: "600",
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 0,
  },
  titleMedium: {
    fontFamily: "System",
    fontWeight: "600",
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: 0.1,
  },
  titleSmall: {
    fontFamily: "System",
    fontWeight: "600",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  bodyLarge: {
    fontFamily: "System",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.2,
  },
  bodyMedium: {
    fontFamily: "System",
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.2,
  },
  bodySmall: {
    fontFamily: "System",
    fontWeight: "400",
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.4,
  },
  labelLarge: {
    fontFamily: "System",
    fontWeight: "500",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.5,
  },
  labelMedium: {
    fontFamily: "System",
    fontWeight: "500",
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  labelSmall: {
    fontFamily: "System",
    fontWeight: "500",
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.5,
  },
};
